Specify non-applicable patch when performing check
Saves time debugging

diff --git a/libs/git b/libs/git
--- a/libs/git
+++ b/libs/git
@@ -235,7 +235,10 @@ git_patch() {
 	local branch=$2
 	local patch=$3
 
-	git_apply_check "$repository_path" "$branch" "$patch" || return 1
+	if ! git_apply_check "$repository_path" "$branch" "$patch"; then
+		printf '%s\n' "Patching failed with: ${patch##*$root/$PROJECTS/}"
+		return 1
+	fi
 
 	case $patch in
 		*.patch)
diff --git a/libs/project b/libs/project
--- a/libs/project
+++ b/libs/project
@@ -695,11 +695,12 @@ project_sources_patch() {
 	local sources_path=$1
 	local patch_path=$2
 
-	if diff_patch_check "$sources_path" "$patch_path"; then
-		diff_patch "$sources_path" "$patch_path"
-	else
+	if ! diff_patch_check "$sources_path" "$patch_path"; then
+		printf '%s\n' "Patching failed with: ${patch_path##*$root/$PROJECTS/}"
 		return 1
 	fi
+
+	diff_patch "$sources_path" "$patch_path"
 }
 
 project_blobs_path() {
